(function exposeTF2Chapters(root) {
  "use strict";

  const chapters = [
    {
      id: "matrix-stack",
      number: "01",
      duration: "~3 min",
      eyebrow: "Familiar ground",
      title: "A matrix stack is already a frame tree",
      summary: "Every push/translate/rotate block creates a local coordinate system relative to its parent. TF2 keeps those relationships outside the draw call, names them, and remembers how they changed over time.",
      details: [
        "The parent transform is still active when the child transform is applied.",
        "Geometry drawn at (0, 0) lands at the child frame's origin in the world.",
        "pop() returns drawing to the parent; a TF lookup can move coordinates between either frame at any time in the buffer.",
      ],
      rosCode: "// p5: nested local coordinates\npush();\ntranslate(robot.x, robot.y);\nrotate(robot.yaw);\ndrawRobotAtLocalOrigin();\npop();\n\n// TF2 names the same relationship\n// parent: map, child: base_link",
      scene: "matrix",
      hint: "Drag base_link. Watch its local point keep the same coordinates while its map position changes.",
      defaultQuery: { target: "map", source: "base_link", timeMode: "latest" },
    },
    {
      id: "data-types",
      number: "02",
      duration: "~4 min",
      eyebrow: "Name the nouns",
      title: "Frame, transform, pose, point, and vector",
      summary: "TF2 becomes much easier once the nouns stop blending together. A frame is a named coordinate system; a transform relates two frames; a pose or point is data expressed in one frame.",
      details: [
        "A point has a location, so translation and rotation both affect it.",
        "A vector represents a direction or displacement, so translation does not affect it.",
        "A pose contains position and orientation; transforming it changes both.",
        "Stamped data adds frame_id and time so TF2 knows which transform sample to use.",
      ],
      rosCode: "geometry_msgs::msg::PointStamped point;\npoint.header.frame_id = \"laser\";\npoint.header.stamp = stamp;\npoint.point.x = 2.0;\n\nauto point_in_map =\n  tf_buffer.transform(point, \"map\");",
      scene: "types",
      hint: "Compare the point and direction arrow: only the point follows frame translation.",
      defaultQuery: { target: "map", source: "sensor", timeMode: "latest" },
    },
    {
      id: "composition",
      number: "03",
      duration: "~5 min",
      eyebrow: "Read right to left",
      title: "Compose transforms, then invert them",
      summary: "This tutorial writes T_target_source for the transform that converts source coordinates into target coordinates. T_map_laser = T_map_base × T_base_laser, so the rightmost transform acts first.",
      details: [
        "Composition follows the connecting frame names: the middle names cancel conceptually.",
        "Order matters because rigid transforms do not commute.",
        "T_laser_map is the inverse of T_map_laser, not a reordered copy of its numbers.",
      ],
      rosCode: "auto map_from_laser = tf_buffer.lookupTransform(\n  \"map\",       // target\n  \"laser\",     // source\n  tf2::TimePointZero\n);\n\n// Result semantics: T_map_laser",
      scene: "compose",
      hint: "Move the sensor offset and compare T_map_laser with its inverse lookup.",
      defaultQuery: { target: "map", source: "laser", timeMode: "latest" },
    },
    {
      id: "tree",
      number: "04",
      duration: "~4 min",
      eyebrow: "Topology before math",
      title: "TF2 is a tree, not a bag of poses",
      summary: "At a given time, every non-root frame has exactly one parent. That gives any connected source and target one unambiguous path through their nearest common ancestor.",
      details: [
        "A child cannot have map and odom as simultaneous parents.",
        "A cycle would make a frame its own ancestor and destroys a unique path.",
        "Disconnected roots cannot answer a lookup because no relationship connects them.",
        "Branches are normal: laser and camera can both be children of base_link.",
      ],
      rosCode: "// Valid branch\nmap -> odom -> base_link -> laser\n                         -> camera\n\n// Invalid: base_link gets another parent\nworld -> base_link  // rejected topology",
      scene: "tree",
      hint: "The highlighted source-to-target route is the only legal path through this tree.",
      defaultQuery: { target: "map", source: "camera", timeMode: "latest" },
    },
    {
      id: "mobile-chain",
      number: "05",
      duration: "~5 min",
      eyebrow: "Canonical robot frames",
      title: "map → odom → base_link → sensors",
      summary: "Mobile robots separate global correction, locally smooth motion, the robot body, and rigidly mounted sensors into different frames. Each edge has one job and usually one authority.",
      details: [
        "map is the globally useful reference produced by localization or SLAM.",
        "odom is the locally continuous reference used for smooth motion.",
        "base_link is rigidly attached to the robot body.",
        "laser and camera describe fixed sensor mounting offsets from the body.",
      ],
      rosCode: "// Typical publishers\nlocalization:          map -> odom\nwheel_odometry:        odom -> base_link\nrobot_state_publisher: base_link -> laser\nrobot_state_publisher: base_link -> camera",
      scene: "mobile",
      hint: "Follow the yellow lookup from laser all the way to map; each edge contributes once.",
      defaultQuery: { target: "map", source: "laser", timeMode: "latest" },
    },
    {
      id: "frame-roles",
      number: "06",
      duration: "~5 min",
      eyebrow: "Smooth here, correct there",
      title: "Why odom drifts while map can jump",
      summary: "odom is continuous but accumulates error. Localization corrects that error through map → odom, allowing the map-frame robot pose to become globally accurate without injecting jumps into the local odometry edge.",
      details: [
        "odom → base_link follows wheel or visual odometry smoothly.",
        "Its estimate can drift away from landmarks over time.",
        "map → odom absorbs localization corrections and may change discontinuously.",
        "Controllers can use odom continuity while planners use map accuracy.",
      ],
      rosCode: "// Localization publishes the correction edge\ngeometry_msgs::msg::TransformStamped correction;\ncorrection.header.frame_id = \"map\";\ncorrection.child_frame_id = \"odom\";\nbroadcaster.sendTransform(correction);",
      scene: "roles",
      hint: "The grey odom trail stays smooth. At the correction pulse, map → odom shifts underneath it.",
      defaultQuery: { target: "map", source: "base_link", timeMode: "latest" },
    },
    {
      id: "broadcasters",
      number: "07",
      duration: "~4 min",
      eyebrow: "Who owns each edge?",
      title: "Static and dynamic broadcasters",
      summary: "A TF edge should have one clear authority. Static transforms describe relationships that do not change, while dynamic transforms are timestamped samples continually published by the subsystem that estimates them.",
      details: [
        "Static sensor mounts are sent once and remain valid for any query time.",
        "Dynamic robot motion carries a new timestamp with every update.",
        "Two nodes fighting over the same child edge create unstable, misleading data.",
        "The tree stores relationships, not ownership arbitration logic.",
      ],
      rosCode: "tf2_ros::StaticTransformBroadcaster static_tf(node);\nstatic_tf.sendTransform(base_from_laser);\n\ntf2_ros::TransformBroadcaster dynamic_tf(node);\ndynamic_tf.sendTransform(odom_from_base);",
      scene: "authority",
      hint: "Dashed edges are static. Solid edges animate and carry changing timestamps.",
      defaultQuery: { target: "map", source: "camera", timeMode: "latest" },
    },
    {
      id: "lookup",
      number: "08",
      duration: "~5 min",
      eyebrow: "Target first, source second",
      title: "Ask: where is source data in target?",
      summary: "lookupTransform(target, source, time) returns T_target_source. Select either endpoint and the tree walks up to a common ancestor, then back down, inverting stored edges where the direction requires it.",
      details: [
        "Target is the coordinate system you want the answer expressed in.",
        "Source is the coordinate system the original data uses.",
        "Looking up the reverse direction produces the inverse transform.",
        "The path, requested time, and every edge must all be available.",
      ],
      rosCode: "auto target_from_source = tf_buffer.lookupTransform(\n  target_frame,\n  source_frame,\n  query_time\n);\n\n// Apply T_target_source to source-frame data.",
      scene: "lookup",
      hint: "Change target and source. INVERSE marks appear when traversal opposes the stored parent-from-child edge.",
      defaultQuery: { target: "map", source: "laser", timeMode: "latest" },
    },
    {
      id: "stamped-data",
      number: "09",
      duration: "~5 min",
      eyebrow: "Coordinates need context",
      title: "Transform stamped points and poses",
      summary: "The same numeric point means different places in different frames. frame_id states where the coordinates live; the timestamp states when; TF2 supplies the matching relationship before transforming the payload.",
      details: [
        "PointStamped transforms position but has no orientation.",
        "Vector3Stamped rotates direction and ignores translation.",
        "PoseStamped transforms both position and orientation.",
        "The output header names the target frame while preserving the relevant time.",
      ],
      rosCode: "geometry_msgs::msg::PoseStamped laser_pose;\nlaser_pose.header.frame_id = \"laser\";\nlaser_pose.header.stamp = stamp;\n\ngeometry_msgs::msg::PoseStamped map_pose;\ntf2::doTransform(laser_pose, map_pose, map_from_laser);",
      scene: "stamped",
      hint: "Point, vector, and pose start with related numbers but respond differently to translation and rotation.",
      defaultQuery: { target: "map", source: "laser", timeMode: "latest" },
    },
    {
      id: "time-buffer",
      number: "10",
      duration: "~6 min",
      eyebrow: "A tree through time",
      title: "TF2 looks up a moment, not just an edge",
      summary: "Dynamic edges are short histories of timestamped transforms. TF2 interpolates inside the shared interval and rejects requests before the oldest or after the newest available sample.",
      details: [
        "An exact timestamp uses the matching sample.",
        "A time between samples interpolates translation and orientation.",
        "TimePointZero requests the latest time shared by every edge in the path.",
        "Past and future extrapolation are data-availability errors, not broken matrix math.",
      ],
      rosCode: "const auto query_time = node->now() - 100ms;\nif (tf_buffer.canTransform(\"map\", \"laser\", query_time)) {\n  auto tf = tf_buffer.lookupTransform(\n    \"map\", \"laser\", query_time);\n}",
      scene: "time",
      hint: "Scrub beyond the green buffered interval to trigger the same categories of extrapolation error TF2 reports.",
      defaultQuery: { target: "map", source: "base_link", timeMode: "slider" },
    },
    {
      id: "sensor-scenario",
      number: "11",
      duration: "~6 min",
      eyebrow: "The full chain",
      title: "A laser observation becomes a map point",
      summary: "A landmark measured in laser coordinates travels through laser → base_link → odom → map. The result should coincide with the world landmark when every edge and timestamp agree.",
      details: [
        "The measurement starts as a PointStamped in laser.",
        "The rigid mount places it in base_link.",
        "Odometry places the robot body in odom.",
        "Localization correction finishes the conversion into map.",
      ],
      rosCode: "auto map_from_laser = tf_buffer.lookupTransform(\n  \"map\", \"laser\", laser_point.header.stamp);\n\ngeometry_msgs::msg::PointStamped map_point;\ntf2::doTransform(laser_point, map_point, map_from_laser);",
      scene: "sensor",
      hint: "The colored intermediate dots are the same observation expressed successively in base_link, odom, and map.",
      defaultQuery: { target: "map", source: "laser", timeMode: "latest" },
    },
    {
      id: "se3",
      number: "12",
      duration: "~6 min",
      eyebrow: "Add Z without changing the tree",
      title: "From SE(2) yaw to SE(3) quaternions",
      summary: "The topology and lookup rules remain the same in 3D. Translation gains Z, orientation becomes a normalized quaternion, and composition rotates each child translation through its parent orientation.",
      details: [
        "Roll, pitch, and yaw are intuitive inputs but depend on rotation order.",
        "Quaternions avoid a singular orientation representation and compose cleanly.",
        "q and -q encode the same physical orientation.",
        "Keep quaternions normalized; do not add their components to compose rotations.",
      ],
      rosCode: "tf2::Quaternion q;\nq.setRPY(roll, pitch, yaw);\nq.normalize();\ntransform.transform.rotation = tf2::toMsg(q);\n\n// The TF tree and lookup API stay unchanged.",
      scene: "se3",
      hint: "Drag to orbit the camera. The RGB axes are the rotated local basis vectors of the child frame.",
      defaultQuery: { target: "map", source: "camera_optical", timeMode: "latest" },
    },
    {
      id: "sandbox",
      number: "13",
      duration: "open lab",
      eyebrow: "Make the tree answer",
      title: "TF2 sandbox",
      summary: "Choose any connected source and target, move the robot, scrub the buffer, and predict T_target_source before reading the result. The tree, world, and numbers all come from the same transforms.",
      details: [
        "Start by naming the frame in which the data currently lives.",
        "Name the frame in which the consumer needs the answer.",
        "Trace the unique path and decide which stored edges need inverses.",
        "Check that every dynamic edge covers the requested time.",
      ],
      rosCode: "if (tf_buffer.canTransform(target, source, stamp)) {\n  const auto target_from_source =\n    tf_buffer.lookupTransform(target, source, stamp);\n  // Transform the stamped payload here.\n}",
      scene: "sandbox",
      hint: "A successful prediction includes direction and time—not only the final x, y, and yaw numbers.",
      defaultQuery: { target: "map", source: "camera", timeMode: "slider" },
    },
  ];

  const TF2_CHAPTERS = Object.freeze(chapters.map((chapter) => Object.freeze({
    ...chapter,
    details: Object.freeze([...chapter.details]),
    defaultQuery: Object.freeze({ ...chapter.defaultQuery }),
  })));

  const api = { TF2_CHAPTERS };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  Object.assign(root, api);
})(typeof window !== "undefined" ? window : globalThis);
